# Generated by Django 3.1.3 on 2022-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220115_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='file',
            new_name='json_file',
        ),
        migrations.AddField(
            model_name='measurement',
            name='npz_file',
            field=models.FileField(default=0, upload_to='measurements/'),
            preserve_default=False,
        ),
    ]
