# Generated by Django 3.1.3 on 2022-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20220126_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='comment',
            field=models.CharField(default='bla', max_length=50),
            preserve_default=False,
        ),
    ]
