# Generated by Django 3.1.3 on 2022-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.TextField(),
        ),
    ]
