# Generated by Django 3.1.3 on 2022-01-11 13:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220111_1310'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
