# Generated by Django 3.1.3 on 2022-01-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220111_1428'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
            ],
        ),
    ]
